import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/Nav";
import Sidebar from "./components/Sidebar";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Nav />
        <div className="flex pl-45">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
